---
title: "MiFish Visualizations"
author: "Zack Gold"
date: "2024-10-20"
output: pdf_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, warning=FALSE, echo=FALSE}
library(tidyverse)
library(DECIPHER)
library(here)
library(patchwork)
```

# Load Data

## MiFish

```{r, warning=FALSE}
Mifish_separated <- readRDS(here("LCA","barcodes_unique","MiFish_12S_vertebrates_only_merged_data_set.RDS"))

Mifish_separated %>% 
  filter(str_detect(lca_taxonomic_path, "Actinopteri|Chondrichthyes|Hyperoartia|Cladistia|Ceratodontiformes")) %>% 
  rowwise() %>%
  mutate(Species_per_cluster = n_distinct(Accesions$Name)) -> Mifish_separated_2

Mifish_separated_2 %>% 
  replace(is.na(.), "") %>% 
  mutate(., Barcode= "MiFish 12S") %>% 
  mutate(., Type = case_when(Species != "" ~ "Species Level ID",
                             Genus != "" ~ "Genus Level ID",
                             Family != "" ~ "Family Level ID",
                             Order != "" ~ "Order Level ID",
                             Class != "" ~ "Class Level ID",
                             Phylum != "" ~ "Phylum Level ID",
                             Domain != "" ~ "Domain Level ID",
                           TRUE  ~ "WEIRD")) -> Mifish_cat

```

## Ford 16S

```{r, warning=FALSE}
Ford_16S_separated <- readRDS(here("LCA","barcodes_unique","Ford_16S_vertebrates_only_merged_data_set.RDS"))

Ford_16S_separated %>% 
    filter(str_detect(lca_taxonomic_path, "Actinopteri|Chondrichthyes|Hyperoartia|Cladistia|Ceratodontiformes")) %>% 
  rowwise() %>%
  mutate(Species_per_cluster = n_distinct(Accesions$Name)) -> Ford_16S_separated_2

Ford_16S_separated_2 %>% 
  replace(is.na(.), "") %>% 
    mutate(., Barcode= "Ford 16S") %>% 
  mutate(., Type = case_when(Species != "" ~ "Species Level ID",
                             Genus != "" ~ "Genus Level ID",
                             Family != "" ~ "Family Level ID",
                             Order != "" ~ "Order Level ID",
                             Class != "" ~ "Class Level ID",
                             Phylum != "" ~ "Phylum Level ID",
                             Domain != "" ~ "Domain Level ID",
                           TRUE  ~ "WEIRD")) -> Ford_16S_cat

```

## MarVer3

```{r, warning=FALSE}
MarVer3_separated <- readRDS(here("LCA","barcodes_unique","MarVer3_vertebrates_only_merged_data_set.RDS"))

MarVer3_separated %>% 
    filter(str_detect(lca_taxonomic_path, "Actinopteri|Chondrichthyes|Hyperoartia|Cladistia|Ceratodontiformes")) %>% 
  rowwise() %>%
  mutate(Species_per_cluster = n_distinct(Accesions$Name)) -> MarVer3_separated_2

MarVer3_separated_2 %>% 
  replace(is.na(.), "") %>% 
      mutate(., Barcode= "MarVer3") %>% 
   mutate(., Type = case_when(Species != "" ~ "Species Level ID",
                             Genus != "" ~ "Genus Level ID",
                             Family != "" ~ "Family Level ID",
                             Order != "" ~ "Order Level ID",
                             Class != "" ~ "Class Level ID",
                             Phylum != "" ~ "Phylum Level ID",
                             Domain != "" ~ "Domain Level ID",
                           TRUE  ~ "WEIRD")) -> MarVer3_cat

```

## MiSebastes

```{r, warning=FALSE}
MiSebastes_separated <- readRDS(here("LCA","barcodes_unique","MiSebastes_vertebrates_only_merged_data_set.RDS"))

MiSebastes_separated %>% 
    filter(str_detect(lca_taxonomic_path, "Actinopteri|Chondrichthyes|Hyperoartia|Cladistia|Ceratodontiformes")) %>% 
  rowwise() %>%
  mutate(Species_per_cluster = n_distinct(Accesions$Name)) -> MiSebastes_separated_2

MiSebastes_separated_2 %>% 
  replace(is.na(.), "") %>% 
        mutate(., Barcode= "MiSebastes") %>% 
   mutate(., Type = case_when(Species != "" ~ "Species Level ID",
                             Genus != "" ~ "Genus Level ID",
                             Family != "" ~ "Family Level ID",
                             Order != "" ~ "Order Level ID",
                             Class != "" ~ "Class Level ID",
                             Phylum != "" ~ "Phylum Level ID",
                             Domain != "" ~ "Domain Level ID",
                           TRUE  ~ "WEIRD")) -> MiSebastes_cat

```

## teleo

```{r, warning=FALSE}
teleo_separated <- readRDS(here("LCA","barcodes_unique","teleo_vertebrates_only_merged_data_set.RDS"))

teleo_separated %>% 
    filter(str_detect(lca_taxonomic_path, "Actinopteri|Chondrichthyes|Hyperoartia|Cladistia|Ceratodontiformes")) %>% 
  rowwise() %>%
  mutate(Species_per_cluster = n_distinct(Accesions$Name)) -> teleo_separated_2

teleo_separated_2 %>% 
  replace(is.na(.), "") %>% 
        mutate(., Barcode= "teleo") %>% 
 mutate(., Type = case_when(Species != "" ~ "Species Level ID",
                             Genus != "" ~ "Genus Level ID",
                             Family != "" ~ "Family Level ID",
                             Order != "" ~ "Order Level ID",
                             Class != "" ~ "Class Level ID",
                             Phylum != "" ~ "Phylum Level ID",
                             Domain != "" ~ "Domain Level ID",
                           TRUE  ~ "WEIRD"))-> teleo_cat

```



```{r, warning=FALSE}
#Colors for plots
library(wesanderson)
wes_palette("GrandBudapest1") -> moon1
wes_palette("GrandBudapest2") -> moon2
wes_palette("Moonrise3") -> moon3
wes_palette("Zissou1") -> moon4
```

# Overall Stats

## MiFish
```{r, warning=FALSE}
Mifish_cat  %>% 
  group_by(Type) %>% 
  dplyr::summarise(n= sum(Species_per_cluster))-> Mifish_cat_sum

Mifish_cat_sum %>% 
  ungroup() %>% 
  dplyr::summarise(tot=sum(n)) -> Mifish_cat_tot

Mifish_cat_sum %>% 
  mutate(tot= Mifish_cat_tot$tot,
         Barcode = "MiFish 12S") %>% 
   mutate(., perc=( n/ tot)) -> Mifish_cat_dat
  
```

## Ford 16S

```{r, warning=FALSE}
Ford_16S_cat  %>% 
  group_by(Type) %>% 
  dplyr::summarise(n= sum(Species_per_cluster))-> Ford_16S_cat_sum

Ford_16S_cat_sum %>% 
  ungroup() %>% 
  dplyr::summarise(tot=sum(n)) -> Ford_16S_cat_tot

Ford_16S_cat_sum %>% 
  mutate(tot= Ford_16S_cat_tot$tot,
         Barcode = "Ford 16S") %>% 
   mutate(., perc=( n/ tot)) -> Ford_16S_cat_dat
  
```

## MarVer3

```{r, warning=FALSE}
MarVer3_cat  %>% 
  group_by(Type) %>% 
  dplyr::summarise(n= sum(Species_per_cluster))-> MarVer3_cat_sum

MarVer3_cat_sum %>% 
  ungroup() %>% 
  dplyr::summarise(tot=sum(n)) -> MarVer3_cat_tot

MarVer3_cat_sum %>% 
  mutate(tot= MarVer3_cat_tot$tot,
         Barcode = "MarVer3") %>% 
   mutate(., perc=( n/ tot)) -> MarVer3_cat_dat
  
```

## MiSebastes

```{r, warning=FALSE}
MiSebastes_cat  %>% 
  group_by(Type) %>% 
  dplyr::summarise(n= sum(Species_per_cluster))-> MiSebastes_cat_sum

MiSebastes_cat_sum %>% 
  ungroup() %>% 
  dplyr::summarise(tot=sum(n)) -> MiSebastes_cat_tot

MiSebastes_cat_sum %>% 
  mutate(tot= MiSebastes_cat_tot$tot,
         Barcode = "MiSebastes") %>% 
   mutate(., perc=( n/ tot)) -> MiSebastes_cat_dat
  
```

## teleo

```{r, warning=FALSE}
teleo_cat  %>% 
  group_by(Type) %>% 
  dplyr::summarise(n= sum(Species_per_cluster))-> teleo_cat_sum

teleo_cat_sum %>% 
  ungroup() %>% 
  dplyr::summarise(tot=sum(n)) -> teleo_cat_tot

teleo_cat_sum %>% 
  mutate(tot= teleo_cat_tot$tot,
         Barcode = "teleo") %>% 
   mutate(., perc=( n/ tot)) -> teleo_cat_dat
  
```



## Combined Plots

```{r}
rbind(Mifish_cat_dat,Ford_16S_cat_dat,MarVer3_cat_dat,MiSebastes_cat_dat,teleo_cat_dat) -> combined_cat_dat

saveRDS(combined_cat_dat, here("LCA","Figures","Fish_ref_dbs_combined_cat_dat.RDS"))

combined_cat_dat$Type <- factor(combined_cat_dat$Type, levels=c("Phylum Level ID", "Order Level ID", 'Class Level ID','Family Level ID','Genus Level ID','Species Level ID'))

combined_cat_dat %>% 
ggplot(., aes(y=perc, color=Type, fill=Type, x=Barcode)) + geom_col() + ylab("Percent") + 
  theme_classic() +
  scale_fill_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4])) +
  scale_color_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4])) + 
  guides(fill=guide_legend(title="Resolution of Taxonomic Identification"), color=guide_legend(title="Resolution of Taxonomic Identification"))+
  scale_y_continuous(labels = scales::percent) +
  geom_hline(yintercept = 1, linetype="dashed") -> a1

a1

ggsave(here("LCA","Figures","Combined_plots_figure_percent.png"), width = 8, height = 6)
```


```{r}

combined_cat_dat %>% 
ggplot(., aes(y=n, color=Type, fill=Type, x=Barcode)) + geom_col() + ylab("Count") + 
  theme_classic() +
scale_fill_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4]))+  scale_colour_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4])) + 
  guides(fill=guide_legend(title="Resolution of Taxonomic Identification"), color=guide_legend(title="Resolution of Taxonomic Identification"))+
  geom_hline(yintercept = 1, linetype="dashed") -> b1

b1

ggsave(here("LCA","Figures","Combined_plots_figure_counts.png"), width = 8, height = 6)

```



## Function to Focus


```{r}

rbind(Mifish_cat,Ford_16S_cat,MarVer3_cat,MiSebastes_cat,teleo_cat) %>% ungroup() -> barcode_cat


```

### Bar Graph
```{r, warning=FALSE}

bar_graph_for_taxa_of_interest <- function(Rank, Taxonomy, barcode_cat) {

ranks = c("Domain","Phylum","Class","Order","Family","Genus","Species")

ranks %>% as.tibble() %>% 
  rownames_to_column() %>% 
  mutate(., rowname=as.numeric(rowname))-> ranks

ranks %>% 
  filter(., value == Rank) -> ranks_f

ranks %>% 
  filter(., rowname == (ranks_f$rowname+1)) -> rank_one_down_to_select

barcode_cat %>%   
      ungroup() %>% 
  filter(., eval(rlang::parse_expr(Rank)) == Taxonomy ) -> barcode_cat_filter

barcode_cat  %>% 
  ungroup() %>% 
  filter(., eval(rlang::parse_expr(Rank)) == Taxonomy ) %>% 
  group_by(across(all_of(c(rank_one_down_to_select$value, "Type","Barcode")))) %>% 
  dplyr::summarise(n= sum(Species_per_cluster)) %>% 
  filter(., eval(rlang::parse_expr(rank_one_down_to_select$value)) !="") %>% 
  arrange(desc(n))-> cat_sum_rank_type_filter

cat_sum_rank_type_filter %>% 
ggplot(., aes(y=n, color=Type, fill=Type, x=reorder(eval(rlang::parse_expr(rank_one_down_to_select$value)), -n))) + 
  geom_col() +
  ylab("Count") + 
  xlab(rank_one_down_to_select$value) +
  theme_classic() +
scale_fill_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4]))+  scale_colour_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4])) + 
  guides(fill=guide_legend(title="Correct Taxonomic Path To:"), color=guide_legend(title="Correct Taxonomic Path To:"))+
    theme(axis.text.x = element_text(angle = 45,hjust = 1)) +facet_wrap(.~ Barcode)-> plot1

plot1

}
```

```{r}
bar_graph_for_taxa_of_interest("Family","Sebastidae",barcode_cat )
bar_graph_for_taxa_of_interest("Family","Labridae",barcode_cat )
bar_graph_for_taxa_of_interest("Family","Carcharhinidae",barcode_cat )
bar_graph_for_taxa_of_interest("Class","Chondrichthyes",barcode_cat )

ggsave(here("LCA","Figures","Chondrichthyes_bar_graph_for_taxa_of_interest.png"), width = 8, height = 6)


```
### Tile Plot

```{r, fig.height=14, fig.width=8, warning=FALSE}

tile_plot_for_taxa_of_interest <- function(Rank, Taxonomy, barcode_cat) {
  
ranks = c("Domain","Phylum","Class","Order","Family","Genus","Species")

ranks %>% as.tibble() %>% 
  rownames_to_column() %>% 
  mutate(., rowname=as.numeric(rowname))-> ranks

ranks %>% 
  filter(., value == Rank) -> ranks_f

ranks %>% 
  filter(., rowname == (ranks_f$rowname+1)) -> rank_one_down_to_select

barcode_cat %>%   
    ungroup() %>% 
  filter(., eval(rlang::parse_expr(Rank)) == Taxonomy ) -> barcode_cat_filter

barcode_cat_filter %>% 
  filter(., Species != "") %>% 
  ungroup() %>% 
  dplyr::select(Barcode,Class, Order, Family, Genus, Species, Type) %>% 
  unite(., `Barcode:Species`, c("Barcode","Species"), sep = ":", remove=F)-> ranks_of_species

barcode_cat_filter %>% 
  filter(., Species =="") %>% 
  unnest(Accesions) %>% 
  ungroup() %>% 
  dplyr::select(Barcode,Name, Type) %>% 
  separate(Name, into=c("Domain","Phylum","Class","Order","Family","Genus","Species"), sep=";", remove=F) %>% 
  dplyr::select(Barcode,Class, Order, Family, Genus, Species, Type) %>% 
  unique() %>% unite(., `Barcode:Species`, c("Barcode","Species"), sep = ":", remove=F)-> ranks_of_higher_tax

ranks_of_higher_tax %>% 
  filter(., !`Barcode:Species` %in% ranks_of_species$`Barcode:Species`) -> ranks_of_higher_tax_clean

rbind(ranks_of_species,ranks_of_higher_tax_clean) %>% 
  mutate(., LCA = case_when(Species !="" ~ Species,
                             Genus !="" ~ Genus,
                             Family !="" ~ Family,
                            Order !="" ~ Order,
                            Class !="" ~ Class,
                             TRUE ~"WEIRD")) %>% 
  ggplot(., aes( y= LCA, x= Barcode, fill =Type)) +geom_tile() +
  theme_classic() + theme(axis.text.x = element_text(angle =30, hjust = 1)) +
 scale_fill_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4]))+  scale_colour_manual(values=c(`Phylum Level ID`=moon2[3], `Order Level ID`=moon3[3],`Class Level ID`=moon3[4],`Family Level ID`=moon3[5],`Genus Level ID`=moon2[2],`Species Level ID`=moon2[4])) +  guides(fill=guide_legend(title="Resolution of Taxonomic Identification"), color=guide_legend(title="Resolution of Taxonomic Identification"))  -> plot2

plot2

}
```

```{r}
tile_plot_for_taxa_of_interest("Genus","Sebastes",barcode_cat )
tile_plot_for_taxa_of_interest("Order","Lamniformes",barcode_cat )
tile_plot_for_taxa_of_interest("Family","Carcharhinidae",barcode_cat )
tile_plot_for_taxa_of_interest("Family","Embiotocidae",barcode_cat )
ggsave(here("LCA","Figures","tile_plot_for_taxa_of_interest_surfperch_figure.png"), width = 8, height = 6)

tile_plot_for_taxa_of_interest("Class","Chondrichthyes",barcode_cat )
tile_plot_for_taxa_of_interest("Class","Hyperoartia",barcode_cat )

```


# Rank accumulation curves to identify which barcode performs the best

## Species
```{r}

barcode_cat %>% 
  filter(., Species != "") %>% 
  ungroup() %>% 
  dplyr::select(Barcode,Class, Order, Family, Genus, Species, Type) %>% 
  unite(., `Barcode:Species`, c("Barcode","Species"), sep = ":", remove=F)-> ranks_of_species

ranks_of_species %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Total_species = n_distinct(Species)) -> tot_species

ranks_of_species %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Species = list(unique(Species))) -> nested_species


library("gplots")
library(rrapply)
rrapply(nested_species, how = "unmelt") -> species_for_venn

v.table <- venn(species_for_venn)

v.table %>% head(n=100) %>%  as.tibble(., rownames = "Group") -> v.tibble
colnames(v.tibble)[3:length(colnames(v.tibble))] -> cols_vec

dat_dict <- tibble(col_nm = cols_vec,
                   value = 1,
                   label=cols_vec)
  
  
recode_col <- function(x) {
  
  recode_vec <- dat_dict |>
    filter(col_nm == cur_column()) |>
    pull(label, name = value)
  
  dplyr::recode(x, !!! recode_vec)
}


v.tibble %>% 
 # mutate(., Names = paste(colnames(v.tibble)[3:length(colnames(v.tibble))],collapse = ':')) %>% 
 
mutate(across(all_of(cols_vec),
                recode_col)
  ) %>% 
  unite(Group_2, cols_vec, sep = ":", na.rm = TRUE) %>% 
  mutate(., levels = str_count(Group_2, ":")+1) -> v_clean


v.tibble %>% 
  left_join(v_clean) %>%  
  filter(., Group!="00000") %>% 
  mutate_at(.funs = funs(. * num), .cols = vars(-Group, -num, -Group_2, -levels)) -> table_analysis


table_analysis %>% 
  summarise(across(where(is.numeric), sum)) %>% 
  dplyr::select(-num, -levels) %>% 
  pivot_longer(cols=everything(), values_to = "Species_total", names_to = "Barcode") -> level_1_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names

level_1_clean %>% 
  full_join(empty_names) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total) %>% 
  mutate(., Level=2,
         level_2_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2"), sep = ":", na.rm = TRUE) -> level_2

table_analysis %>% 
  left_join(level_2) %>% 
  filter(., !is.na(level_2_sum)) %>% 
  mutate(., level_2_unique_tot= level_2_sum-num ) %>% 
  arrange(desc(level_2_unique_tot)) -> level_2_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names_3


level_1_clean %>% 
  full_join(empty_names_3) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total, Barcode=`Barcode...3`) %>% 
    left_join(level_1_clean)  %>% 
   dplyr::rename(Barcode_3=Barcode, `Barcode_3:Species_total`=Species_total) %>% 
  mutate(., Level=3,
         level_3_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total` + `Barcode_3:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2", "Barcode_3"), sep = ":", na.rm = TRUE) -> level_3

table_analysis %>% 
  filter(., levels %in% c(2)) %>% 
  dplyr::select(num, Group_2) %>% 
  separate(Group_2, into=c("Barcode1","Barcode2"), sep=":", remove = F) -> level_2_split

table_analysis %>% 
  left_join(level_3) %>% 
  filter(., !is.na(level_3_sum)) -> level3_to_include

empty_names_3 %>% 
  unite(Group_2, c("Barcode","Barcode...2", "Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  unite(Group_12, c("Barcode","Barcode...2"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_12"="Group_2")) %>% 
  dplyr::rename(num12=num) %>% 
  unite(Group_13, c("Barcode","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_13"="Group_2")) %>% 
  dplyr::rename(num13=num) %>% 
  unite(Group_23, c("Barcode...2","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_23"="Group_2")) %>% 
  dplyr::rename(num23=num) -> level_3__paired_intersects

level3_to_include %>% 
  left_join(level_3__paired_intersects) %>% 
  mutate(., level_3_unique_tot= level_3_sum-num-num13-num12-num23 ) %>% 
  arrange(desc(level_3_unique_tot)) -> level_3_clean



```

```{r}
level_1_clean %>% 
  arrange(desc(Species_total)) %>% 
  dplyr::slice(1) -> intersection_1_clean

level_2_clean %>% 
  arrange(desc(level_2_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_2_clean

level_3_clean %>% 
  arrange(desc(level_3_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_3_clean
  
tibble(
total_species = c(intersection_1_clean$Species_total[[1]], 
                   intersection_2_clean$level_2_unique_tot[[1]],
                   intersection_3_clean$level_3_unique_tot[[1]]),
Barcode = c(intersection_1_clean$Barcode[[1]], 
           intersection_2_clean$Group_2[[1]],
               intersection_3_clean$Group_2[[1]]     ),
Level="Species"
) -> tibble_for_plotting

```
## Genus

```{r}

barcode_cat %>% 
  filter(., Genus != "") %>% 
  ungroup() %>% 
  dplyr::select(Barcode,Class, Order, Family, Genus, Species, Type) %>% 
  unite(., `Barcode:Genus`, c("Barcode","Genus"), sep = ":", remove=F)-> ranks_of_Genus

ranks_of_Genus %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Total_species = n_distinct(Genus)) -> tot_Genus

ranks_of_Genus %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Genus = list(unique(Genus))) -> nested_Genus


library("gplots")
library(rrapply)
rrapply(nested_Genus, how = "unmelt") -> genus_for_venn

v.table <- venn(genus_for_venn)

v.table %>% head(n=100) %>%  as.tibble(., rownames = "Group") -> v.tibble
colnames(v.tibble)[3:length(colnames(v.tibble))] -> cols_vec

dat_dict <- tibble(col_nm = cols_vec,
                   value = 1,
                   label=cols_vec)
  
  
recode_col <- function(x) {
  
  recode_vec <- dat_dict |>
    filter(col_nm == cur_column()) |>
    pull(label, name = value)
  
  dplyr::recode(x, !!! recode_vec)
}


v.tibble %>% 
 # mutate(., Names = paste(colnames(v.tibble)[3:length(colnames(v.tibble))],collapse = ':')) %>% 
 
mutate(across(all_of(cols_vec),
                recode_col)
  ) %>% 
  unite(Group_2, cols_vec, sep = ":", na.rm = TRUE) %>% 
  mutate(., levels = str_count(Group_2, ":")+1) -> v_clean


v.tibble %>% 
  left_join(v_clean) %>%  
  filter(., Group!="00000") %>% 
  mutate_at(.funs = funs(. * num), .cols = vars(-Group, -num, -Group_2, -levels)) -> table_analysis


table_analysis %>% 
  summarise(across(where(is.numeric), sum)) %>% 
  dplyr::select(-num, -levels) %>% 
  pivot_longer(cols=everything(), values_to = "Species_total", names_to = "Barcode") -> level_1_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names

level_1_clean %>% 
  full_join(empty_names) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total) %>% 
  mutate(., Level=2,
         level_2_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2"), sep = ":", na.rm = TRUE) -> level_2

table_analysis %>% 
  left_join(level_2) %>% 
  filter(., !is.na(level_2_sum)) %>% 
  mutate(., level_2_unique_tot= level_2_sum-num ) %>% 
  arrange(desc(level_2_unique_tot)) -> level_2_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names_3


level_1_clean %>% 
  full_join(empty_names_3) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total, Barcode=`Barcode...3`) %>% 
    left_join(level_1_clean)  %>% 
   dplyr::rename(Barcode_3=Barcode, `Barcode_3:Species_total`=Species_total) %>% 
  mutate(., Level=3,
         level_3_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total` + `Barcode_3:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2", "Barcode_3"), sep = ":", na.rm = TRUE) -> level_3

table_analysis %>% 
  filter(., levels %in% c(2)) %>% 
  dplyr::select(num, Group_2) %>% 
  separate(Group_2, into=c("Barcode1","Barcode2"), sep=":", remove = F) -> level_2_split

table_analysis %>% 
  left_join(level_3) %>% 
  filter(., !is.na(level_3_sum)) -> level3_to_include

empty_names_3 %>% 
  unite(Group_2, c("Barcode","Barcode...2", "Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  unite(Group_12, c("Barcode","Barcode...2"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_12"="Group_2")) %>% 
  dplyr::rename(num12=num) %>% 
  unite(Group_13, c("Barcode","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_13"="Group_2")) %>% 
  dplyr::rename(num13=num) %>% 
  unite(Group_23, c("Barcode...2","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_23"="Group_2")) %>% 
  dplyr::rename(num23=num) -> level_3__paired_intersects

level3_to_include %>% 
  left_join(level_3__paired_intersects) %>% 
  mutate(., level_3_unique_tot= level_3_sum-num-num13-num12-num23 ) %>% 
  arrange(desc(level_3_unique_tot)) -> level_3_clean



```

```{r}
level_1_clean %>% 
  arrange(desc(Species_total)) %>% 
  dplyr::slice(1) -> intersection_1_clean

level_2_clean %>% 
  arrange(desc(level_2_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_2_clean

level_3_clean %>% 
  arrange(desc(level_3_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_3_clean
  
tibble(
total_species = c(intersection_1_clean$Species_total[[1]], 
                   intersection_2_clean$level_2_unique_tot[[1]],
                   intersection_3_clean$level_3_unique_tot[[1]]),
Barcode = c(intersection_1_clean$Barcode[[1]], 
           intersection_2_clean$Group_2[[1]],
               intersection_3_clean$Group_2[[1]]     ),
Level="Genus"
) -> tibble_for_plotting_genus

```

## Family

```{r}

barcode_cat %>% 
  filter(., Family != "") %>% 
  ungroup() %>% 
  dplyr::select(Barcode,Class, Order, Family, Genus, Species, Type) %>% 
  unite(., `Barcode:Family`, c("Barcode","Family"), sep = ":", remove=F)-> ranks_of_Family

ranks_of_Family %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Total_species = n_distinct(Family)) -> tot_Family

ranks_of_Family %>% 
  group_by(Barcode) %>% 
  dplyr::summarise(Family = list(unique(Family))) -> nested_Family


library("gplots")
library(rrapply)
rrapply(nested_Family, how = "unmelt") -> Family_for_venn

v.table <- venn(Family_for_venn)

v.table %>% head(n=100) %>%  as.tibble(., rownames = "Group") -> v.tibble
colnames(v.tibble)[3:length(colnames(v.tibble))] -> cols_vec

dat_dict <- tibble(col_nm = cols_vec,
                   value = 1,
                   label=cols_vec)
  
  
recode_col <- function(x) {
  
  recode_vec <- dat_dict |>
    filter(col_nm == cur_column()) |>
    pull(label, name = value)
  
  dplyr::recode(x, !!! recode_vec)
}


v.tibble %>% 
 # mutate(., Names = paste(colnames(v.tibble)[3:length(colnames(v.tibble))],collapse = ':')) %>% 
 
mutate(across(all_of(cols_vec),
                recode_col)
  ) %>% 
  unite(Group_2, cols_vec, sep = ":", na.rm = TRUE) %>% 
  mutate(., levels = str_count(Group_2, ":")+1) -> v_clean


v.tibble %>% 
  left_join(v_clean) %>%  
  filter(., Group!="00000") %>% 
  mutate_at(.funs = funs(. * num), .cols = vars(-Group, -num, -Group_2, -levels)) -> table_analysis


table_analysis %>% 
  summarise(across(where(is.numeric), sum)) %>% 
  dplyr::select(-num, -levels) %>% 
  pivot_longer(cols=everything(), values_to = "Species_total", names_to = "Barcode") -> level_1_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names

level_1_clean %>% 
  full_join(empty_names) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total) %>% 
  mutate(., Level=2,
         level_2_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2"), sep = ":", na.rm = TRUE) -> level_2

table_analysis %>% 
  left_join(level_2) %>% 
  filter(., !is.na(level_2_sum)) %>% 
  mutate(., level_2_unique_tot= level_2_sum-num ) %>% 
  arrange(desc(level_2_unique_tot)) -> level_2_clean

level_1_clean %>% 
  tidyr::expand(Barcode, Barcode, Barcode) %>% 
  dplyr::rename(Barcode=`Barcode...1`)-> empty_names_3


level_1_clean %>% 
  full_join(empty_names_3) %>% 
  dplyr::rename(Barcode_1=Barcode, `Barcode_1:Species_total`=Species_total, Barcode=`Barcode...2`) %>% 
  left_join(level_1_clean) %>% 
  dplyr::rename(Barcode_2=Barcode, `Barcode_2:Species_total`=Species_total, Barcode=`Barcode...3`) %>% 
    left_join(level_1_clean)  %>% 
   dplyr::rename(Barcode_3=Barcode, `Barcode_3:Species_total`=Species_total) %>% 
  mutate(., Level=3,
         level_3_sum = `Barcode_1:Species_total` + `Barcode_2:Species_total` + `Barcode_3:Species_total`) %>% 
unite(Group_2, c("Barcode_1","Barcode_2", "Barcode_3"), sep = ":", na.rm = TRUE) -> level_3

table_analysis %>% 
  filter(., levels %in% c(2)) %>% 
  dplyr::select(num, Group_2) %>% 
  separate(Group_2, into=c("Barcode1","Barcode2"), sep=":", remove = F) -> level_2_split

table_analysis %>% 
  left_join(level_3) %>% 
  filter(., !is.na(level_3_sum)) -> level3_to_include

empty_names_3 %>% 
  unite(Group_2, c("Barcode","Barcode...2", "Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  unite(Group_12, c("Barcode","Barcode...2"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_12"="Group_2")) %>% 
  dplyr::rename(num12=num) %>% 
  unite(Group_13, c("Barcode","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_13"="Group_2")) %>% 
  dplyr::rename(num13=num) %>% 
  unite(Group_23, c("Barcode...2","Barcode...3"), sep = ":", na.rm = TRUE, remove=F) %>% 
  left_join(level_2_split, by=c("Group_23"="Group_2")) %>% 
  dplyr::rename(num23=num) -> level_3__paired_intersects

level3_to_include %>% 
  left_join(level_3__paired_intersects) %>% 
  mutate(., level_3_unique_tot= level_3_sum-num-num13-num12-num23 ) %>% 
  arrange(desc(level_3_unique_tot)) -> level_3_clean



```

```{r}
level_1_clean %>% 
  arrange(desc(Species_total)) %>% 
  dplyr::slice(1) -> intersection_1_clean

level_2_clean %>% 
  arrange(desc(level_2_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_2_clean

level_3_clean %>% 
  arrange(desc(level_3_unique_tot)) %>% 
  dplyr::slice(1) -> intersection_3_clean
  
tibble(
total_species = c(intersection_1_clean$Species_total[[1]], 
                   intersection_2_clean$level_2_unique_tot[[1]],
                   intersection_3_clean$level_3_unique_tot[[1]]),
Barcode = c(intersection_1_clean$Barcode[[1]], 
           intersection_2_clean$Group_2[[1]],
               intersection_3_clean$Group_2[[1]]     ),
Level="Family"
) -> tibble_for_plotting_Family

```

## Plot 

```{r plot-accumulation-curve-taxa}

# set colors
my_pal <- c("steelblue", "darkcyan", "darkseagreen3")


rbind(tibble_for_plotting, tibble_for_plotting_genus, tibble_for_plotting_Family) %>% 
  ggplot() +
  theme_bw() +
  expand_limits(y = 0) +
  xlab("Locus") + 
  ylab("Reference species") +
  labs(color = "Taxonomic rank") +
    labs(linetype = "Taxonomic rank") +
  scale_color_manual(values = my_pal) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 0.95),
    #axis.text.x = element_blank(),
    axis.title.x = element_text(margin = margin(t = 10), size = 11),
    axis.title.y = element_text(margin = margin(r = 10), size = 11),
    legend.text = element_text(size = 10),
    #legend.title = element_text(size = 12),
    legend.position="none",
    legend.title = element_blank()
  ) + facet_wrap(~Level, scales = "free") +
  geom_point(aes(x = reorder(Barcode, total_species), y = total_species, color = Level)) +
  geom_line(aes(x = reorder(Barcode, total_species), y = total_species, color = Level, group = Level, linetype = Level)) -> plot3

plot3

ggsave(here("LCA","Figures","rank_accumulation_curve.png"), width = 8, height = 6)

```


