---
title: "Species List Clean and Parse"
author: "Sean McAllister"
date: "2024-10-18"
output: html_document
---

# Load in Libraries
```{r}
library(tidyverse)
library(here)
library(readxl)
library(stringr)
library(worrms)
library(readr)
```

# Load in Data #Raw from NEP merge.Rmd
```{r}
NEP_list_assembled_raw <- read_delim(here("gap_analysis_code","01_inputs","NEP_list_assembled_raw.txt"), col_types = "c", na = c("","NA"))

CCLME_list_assembled_raw <- read.csv(here("FishCARD_copy_20240804","Data","CA_fish_species","CA_fish_list_20210216.csv"))

CCLME_list_assembled_raw %>% 
  mutate(., Source= "Walker_Miller_Lea_Combo_20210216") %>% 
  rename(Scientific.Name=Walker_Miller_Lea_Combo_20210216 ) -> CCLME_list_assembled_raw

CCLME_list_assembled_raw$Scientific.Name %>% unique() %>%  length()
```

# CLEAN PROCESS
## Remove empty scientific.name
```{r}
CCLME_list_assembled_clean <- CCLME_list_assembled_raw %>%
  filter(!(is.na(Scientific.Name) | Scientific.Name == "NA"))
```

## Manually Fix instances of a presumed identical genus name in list
```{r}
# Identify entries with abbreviated genus names
CCLME_list_assembled_clean %>%
  filter(str_detect(Scientific.Name, "\\b\\w\\.\\s\\w+")) -> genus_combos
```

## Manually Fix instances of parentheses
```{r}
CCLME_list_assembled_clean %>%
  filter(str_detect(Scientific.Name, "\\(|\\)|\\[|\\]")) -> paren_combos
```

## Check for ";" delimited nested list
```{r}
CCLME_list_assembled_clean %>% 
  filter(., str_detect(Scientific.Name, ";")) -> semicolon_combos

semicolon_combos %>% 
  filter(., str_detect(Scientific.Name, "AND")) -> semi_and

CCLME_list_assembled_clean <- CCLME_list_assembled_clean %>%
  separate_rows(Scientific.Name, sep = ";") %>%
  mutate(Scientific.Name = str_trim(Scientific.Name))  #Trim any extra whitespace

CCLME_list_assembled_clean %>%
 filter(., str_detect(Scientific.Name, ";")) -> semicolon_combos

semicolon_combos
```

## Check for "AND"
```{r}
CCLME_list_assembled_clean %>% 
  filter(., str_detect(Scientific.Name, " AND ")) -> AND_combos

AND_combos

CCLME_list_assembled_clean <- CCLME_list_assembled_clean %>%
  mutate(Scientific.Name = str_replace(Scientific.Name, " AND ", ""))

CCLME_list_assembled_clean %>% 
  filter(., str_detect(Scientific.Name, " AND ")) -> AND_combos

AND_combos
```

## Check for Splits

```{r}
CCLME_list_assembled_clean %>% 
  filter(., str_detect(Scientific.Name, ",")) -> funky_combos

CCLME_list_assembled_clean <- CCLME_list_assembled_clean %>%
  separate_rows(Scientific.Name, sep = ",") %>%
  mutate(Scientific.Name = str_trim(Scientific.Name))  #Trim any extra whitespace

CCLME_list_assembled_clean %>% 
  filter(., str_detect(Scientific.Name, ",")) -> funky_combos
```

## Remove trailing sp, spp, sp., spp.
```{r}
CCLME_list_assembled_clean <- CCLME_list_assembled_clean %>%
  mutate(Scientific.Name = str_replace(Scientific.Name, "\\s*\\b(SP|SPP|SP\\.|SPP\\.)\\s*$", ""))
```

## Manually identify all weird entries
```{r}
CCLME_list_assembled_clean %>%
  filter(str_detect(Scientific.Name, "[^a-zA-Z0-9\\s]")) -> non_alphanumeric_combos
```

# Export cleaned list
```{r}
write.table(CCLME_list_assembled_clean, file=here("gap_analysis_code","00_scripts","fishcard_attempt",'CCLME_list_assembled_clean.txt'), sep='\t', quote=FALSE, row.names=FALSE, col.names = TRUE)

```
